name: la_icons
description: Line Awesome Icons 1.3.0 (by www.icons8.com) library for Flutter
version: 1.0.0
repository: https://github.com/galonsos/la_icons
homepage: https://galonsos.github.io/la_icons/
issue_tracker: https://github.com/galonsos/la_icons/issues
topics:
  - icons
  - ui
  - font
  - customization

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: la-brands-400
      fonts:
        - asset: lib/assets/fonts/la-brands-400.ttf
          weight: 400
    - family: la-regular-400
      fonts:
        - asset: lib/assets/fonts/la-regular-400.ttf
          weight: 400
    - family: la-solid-900
      fonts:
        - asset: lib/assets/fonts/la-solid-900.ttf
          weight: 900
